// Writes site/data.js: every colour the landing page demos show, taken from the real engine and
// stylesheet, so the site can never show a colour Nightcell would not draw.
// Run after changing engine.js or ui.css:  node scripts/site-data.mjs
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(path.join(root, p), 'utf8');
const THEMES = ['graphite', 'midnight', 'oled', 'dim'];

function engineFor(theme) {
  class Ctx {
    get fillStyle() { return this._f || '#000000'; } set fillStyle(v) { this._f = v; }
    get strokeStyle() { return this._s || '#000000'; } set strokeStyle(v) { this._s = v; }
    get font() { return this._font || '10px sans-serif'; } set font(v) { this._font = v; }
    fillRect() {} fill() {} fillText() {} stroke() {} strokeRect() {}
  }
  const store = new Map([['nightcell:state:v1', JSON.stringify({ on: true, theme })]]);
  const el = { setAttribute() {}, removeAttribute() {}, hasAttribute: () => false, style: { setProperty() {}, removeProperty() {} } };
  const ctx = { window: { CanvasRenderingContext2D: Ctx, devicePixelRatio: 2 },
    document: { documentElement: el, addEventListener() {}, dispatchEvent: () => true },
    localStorage: { getItem: (k) => store.get(k) ?? null }, CustomEvent: class {}, MutationObserver: class { observe() {} },
    CanvasRenderingContext2D: Ctx, console };
  ctx.window.window = ctx.window;
  vm.createContext(ctx);
  vm.runInContext(read('extension/src/font.js'), ctx);
  vm.runInContext(read('extension/src/engine.js'), ctx);
  return ctx.window.__nightcellEngine;
}

// Sheets' own light colours for the demo sheet: cell fills, ink, the row/column headers, gridlines
const FILL = { white: '#ffffff', head: '#c9daf8', yellow: '#fff2cc', green: '#d9ead3', red: '#f4cccc', blue: '#cfe2f3', orange: '#fce5cd', axis: '#f8f9fa' };
const INK = { ink: '#000000', grey: '#666666', red: '#ff0000', green: '#38761d', blue: '#1155cc', axis: '#444746' };
const LINE = '#e2e3e3';

// The interface around the grid, per theme, as ui.css sets it
const css = read('extension/src/ui.css');
const block = (sel) => { const i = css.indexOf(sel); return i < 0 ? '' : css.slice(i, css.indexOf('}', i)); };
const token = (b, k) => (new RegExp('--nc-' + k + ':\\s*(#[0-9a-f]{6})', 'i').exec(b) || [])[1];
const base = block('html[data-nightcell="on"] {');
const chrome = Object.fromEntries(THEMES.map((t) => {
  const b = t === 'graphite' ? base : block(`html[data-nightcell="on"][data-nightcell-theme="${t}"]`);
  return [t, Object.fromEntries(['app', 'raised', 'input', 'border', 'text'].map((k) => [k, token(b, k) || token(base, k)]))];
}));

// The same 180 pairs as test/engine.test.mjs
const PAIR_FILLS = ['#ffffff', '#f3f3f3', '#fff2cc', '#d9ead3', '#cfe2f3', '#f4cccc', '#fee2e2', '#86efac', '#fde68a', '#f87171',
  '#2563eb', '#166534', '#7c3aed', '#000000', '#1f2937', '#d3e3fd', '#f8f9fa', '#4285f4', '#ff0000', '#ffff00'];
const PAIR_TEXTS = ['#000000', '#444746', '#6b7280', '#ffffff', '#ff0000', '#1155cc', '#16a34a', '#dc2626', '#041e49'];
const lum = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
  .map((c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)).reduce((a, c, i) => a + c * [0.2126, 0.7152, 0.0722][i], 0);
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };

const themes = {}, minContrast = {};
let pairs = [];
for (const t of THEMES) {
  const e = engineFor(t);
  themes[t] = {
    fill: Object.fromEntries(Object.entries(FILL).map(([k, v]) => [k, e.remap('grid', 'bg', v)])),
    ink: Object.fromEntries(Object.entries(INK).map(([k, v]) => [k, e.remap('grid', 'fg', v)])),
    line: e.remap('grid', 'line', LINE),
    chrome: chrome[t],
  };
  const list = [];
  for (const t1 of PAIR_TEXTS) for (const f of PAIR_FILLS) {
    const bg = e.remap('grid', 'bg', f), fg = e.remap('grid', 'fg', t1);
    list.push([f, t1, bg, fg, +ratio(bg, fg).toFixed(2)]);
  }
  minContrast[t] = Math.min(...list.map((p) => p[4]));
  if (t === 'graphite') pairs = list;
}

const manifest = JSON.parse(read('extension/manifest.json'));
const zip = path.join(root, 'site/nightcell.zip');
const data = {
  version: manifest.version,
  zipKB: Math.round(statSync(zip).size / 1000),
  light: { fill: FILL, ink: INK, line: LINE },
  themes,
  pairs,
  minContrast,
  permissions: manifest.permissions,
  hosts: manifest.host_permissions,
};
writeFileSync(path.join(root, 'site/data.js'),
  '// Generated by scripts/site-data.mjs from the extension source. Do not edit by hand.\nwindow.NC_DATA = ' + JSON.stringify(data) + ';\n');
console.log('site/data.js', data.version, data.zipKB + ' KB zip', 'min contrast', JSON.stringify(minContrast));
